/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerInterGraf;
import domain.enums.SituacaoVeiculo;

/**
 *
 * @author joaom
 */
public class CadastrosSistema extends javax.swing.JDialog {
    
    private GerInterGraf gerIG;
    
    private SituacaoVeiculo sitVeiculo;
    /**
     * Creates new form CadastroVeiculo
     */
    public CadastrosSistema(java.awt.Frame parent, boolean modal, GerInterGraf gerIG) {
        super(parent, modal);
        this.gerIG = gerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LabTituloNovaReserva = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        PanCarros = new javax.swing.JPanel();
        PainelDados = new javax.swing.JPanel();
        TFNome = new javax.swing.JFormattedTextField();
        labCPF = new javax.swing.JLabel();
        LabNome = new javax.swing.JLabel();
        labFeedback = new javax.swing.JLabel();
        labFeedback1 = new javax.swing.JLabel();
        labFeedback2 = new javax.swing.JLabel();
        CBSitVeiculo = new javax.swing.JComboBox<>();
        labFeedback3 = new javax.swing.JLabel();
        labFeedback4 = new javax.swing.JLabel();
        labFeedback5 = new javax.swing.JLabel();
        TFModelo = new javax.swing.JFormattedTextField();
        TFTipo = new javax.swing.JFormattedTextField();
        TFValDiaria = new javax.swing.JFormattedTextField();
        TFNomeLocadora = new javax.swing.JFormattedTextField();
        TFMarca = new javax.swing.JFormattedTextField();
        TFPlaca = new javax.swing.JFormattedTextField();
        BotaoCadastrarVeiculo = new javax.swing.JButton();
        BotaoLimparVeiculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanBarraLateral = new javax.swing.JPanel();
        PanTitleBarraLateral = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        LabAluguelDeCarros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BotaoConfirmar2 = new javax.swing.JButton();
        BotaoLimpar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labFeedback7 = new javax.swing.JLabel();
        LabNome1 = new javax.swing.JLabel();
        TFNome1 = new javax.swing.JFormattedTextField();
        CBSitVeiculo1 = new javax.swing.JComboBox<>();
        TFPlaca1 = new javax.swing.JFormattedTextField();
        labCPF1 = new javax.swing.JLabel();
        labFeedback6 = new javax.swing.JLabel();
        TFModelo1 = new javax.swing.JFormattedTextField();
        BotaoCadastrarLocadora = new javax.swing.JButton();
        BotaoLimparLocadora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanBackground.setForeground(new java.awt.Color(255, 255, 255));
        PanBackground.setMinimumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setPreferredSize(new java.awt.Dimension(1360, 720));
        PanBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(150, 150, 150));
        jPanel1.setForeground(new java.awt.Color(150, 150, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 100));

        LabTituloNovaReserva.setBackground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabTituloNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setText("Cadastros do Sistema");

        BotaoVoltar.setBackground(new java.awt.Color(150, 150, 150));
        BotaoVoltar.setForeground(new java.awt.Color(150, 150, 150));
        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        BotaoVoltar.setBorder(null);
        BotaoVoltar.setBorderPainted(false);
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BotaoVoltar)
                .addGap(36, 36, 36)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoVoltar)
                    .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        PanBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 1020, 110));

        PanCarros.setBackground(new java.awt.Color(255, 255, 255));
        PanCarros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanBackground.add(PanCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 890, -1));

        PainelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Veículo"));

        labCPF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labCPF.setText("Modelo");

        LabNome.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabNome.setText("Foto");

        labFeedback.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback.setText("Placa");

        labFeedback1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback1.setText("Valor Diária");

        labFeedback2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback2.setText("Situação Veiculo");

        labFeedback3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback3.setText("Tipo");

        labFeedback4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback4.setText("Locadora");

        labFeedback5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback5.setText("Marca");

        BotaoCadastrarVeiculo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoCadastrarVeiculo.setText("Cadastrar");
        BotaoCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarVeiculoActionPerformed(evt);
            }
        });

        BotaoLimparVeiculo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoLimparVeiculo.setText("Limpar");
        BotaoLimparVeiculo.setToolTipText("");
        BotaoLimparVeiculo.setActionCommand("");
        BotaoLimparVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabNome)
                    .addComponent(labCPF)
                    .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labFeedback2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labFeedback, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TFModelo)
                        .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CBSitVeiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TFPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labFeedback3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFeedback1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFeedback4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFeedback5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFNomeLocadora)
                    .addComponent(TFMarca)
                    .addComponent(TFValDiaria)
                    .addComponent(TFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoLimparVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFeedback3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFeedback1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFValDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFeedback4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNomeLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFeedback5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabNome))
                        .addGap(18, 18, 18)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labCPF)
                            .addComponent(TFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFeedback)
                            .addComponent(TFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBSitVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFeedback2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLimparVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanBackground.add(PainelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 530, 300));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Preencha os campos a seguir para realizar a reserva");
        PanBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        PanBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setForeground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setMinimumSize(new java.awt.Dimension(370, 550));
        PanBarraLateral.setPreferredSize(new java.awt.Dimension(360, 720));
        PanBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitleBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanTitleBarraLateral.setForeground(new java.awt.Color(51, 51, 51));

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        LabPrimeDrive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabPrimeDrive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        LabAluguelDeCarros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        LabAluguelDeCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabAluguelDeCarros.setText("Aluguel de carros");
        LabAluguelDeCarros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabAluguelDeCarros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanTitleBarraLateralLayout = new javax.swing.GroupLayout(PanTitleBarraLateral);
        PanTitleBarraLateral.setLayout(PanTitleBarraLateralLayout);
        PanTitleBarraLateralLayout.setHorizontalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabPrimeDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanTitleBarraLateralLayout.setVerticalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(LabPrimeDrive))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanBarraLateral.add(PanTitleBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 110));
        PanBarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 13));

        PanBackground.add(PanBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        BotaoConfirmar2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoConfirmar2.setText("Confirmar");
        BotaoConfirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConfirmar2ActionPerformed(evt);
            }
        });
        PanBackground.add(BotaoConfirmar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 680, 110, 30));

        BotaoLimpar1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoLimpar1.setText("Limpar");
        BotaoLimpar1.setToolTipText("");
        BotaoLimpar1.setActionCommand("");
        BotaoLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimpar1ActionPerformed(evt);
            }
        });
        PanBackground.add(BotaoLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 680, 110, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Locadora"));

        labFeedback7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback7.setText("Situação Veiculo");

        LabNome1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabNome1.setText("CNPJ");

        labCPF1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labCPF1.setText("Nome");

        labFeedback6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFeedback6.setText("Telefone");

        BotaoCadastrarLocadora.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoCadastrarLocadora.setText("Cadastrar");
        BotaoCadastrarLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarLocadoraActionPerformed(evt);
            }
        });

        BotaoLimparLocadora.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoLimparLocadora.setText("Limpar");
        BotaoLimparLocadora.setToolTipText("");
        BotaoLimparLocadora.setActionCommand("");
        BotaoLimparLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparLocadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BotaoLimparLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoCadastrarLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabNome1)
                            .addComponent(labCPF1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labFeedback7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labFeedback6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFModelo1)
                                .addComponent(TFNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CBSitVeiculo1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFPlaca1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabNome1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCPF1)
                    .addComponent(TFModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFeedback6)
                    .addComponent(TFPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBSitVeiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFeedback7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastrarLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLimparLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanBackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        gerIG.voltarPag(this);
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoLimparVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparVeiculoActionPerformed
//        private void LimparCampos(){
//            TFNome.setText("");
//            FTCPF.setText("");
//            CBCidades.setSelectedItem(0);
//            CBCarros.setSelectedItem(0);
//            FTDataRetirada.setText("");
//            FTDataDevolucao.setText("");
//            FTHorarioRetirada.setText("");
//            FTHorarioDevolucao.setText("");
//        }
    }//GEN-LAST:event_BotaoLimparVeiculoActionPerformed

    private void BotaoCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarVeiculoActionPerformed

        //        try {
            //            Reserva r = new Reserva(
                //                    TFNome.getText(),
                //                    FTCPF.getText(),
                //                    CBCidades.getSelectedItem().toString(),
                //                    CBCarros.getSelectedItem().toString(),
                //                    Util.df.parse(FTDataRetirada.getText()),
                //                    Util.df.parse(FTDataDevolucao.getText()),
                //                    FTHorarioRetirada.getText(),
                //                    FTHorarioDevolucao.getText()
                //            );
            //            tableModelReserva.adicionar(r);
            //
            //        } catch (ParseException ex) {
            //            Logger.getLogger(DlgNovaReserva.class.getName()).log(Level.SEVERE, null, ex);
            //        }

//        LimparCampos();
    }//GEN-LAST:event_BotaoCadastrarVeiculoActionPerformed

    private void BotaoConfirmar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConfirmar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoConfirmar2ActionPerformed

    private void BotaoLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimpar1ActionPerformed

    private void BotaoLimparLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparLocadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimparLocadoraActionPerformed

    private void BotaoCadastrarLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarLocadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastrarLocadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarLocadora;
    private javax.swing.JButton BotaoCadastrarVeiculo;
    private javax.swing.JButton BotaoConfirmar2;
    private javax.swing.JButton BotaoLimpar1;
    private javax.swing.JButton BotaoLimparLocadora;
    private javax.swing.JButton BotaoLimparVeiculo;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JComboBox<String> CBSitVeiculo;
    private javax.swing.JComboBox<String> CBSitVeiculo1;
    private javax.swing.JLabel LabAluguelDeCarros;
    private javax.swing.JLabel LabNome;
    private javax.swing.JLabel LabNome1;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabTituloNovaReserva;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PanBackground;
    private javax.swing.JPanel PanBarraLateral;
    private javax.swing.JPanel PanCarros;
    private javax.swing.JPanel PanTitleBarraLateral;
    private javax.swing.JFormattedTextField TFMarca;
    private javax.swing.JFormattedTextField TFModelo;
    private javax.swing.JFormattedTextField TFModelo1;
    private javax.swing.JFormattedTextField TFNome;
    private javax.swing.JFormattedTextField TFNome1;
    private javax.swing.JFormattedTextField TFNomeLocadora;
    private javax.swing.JFormattedTextField TFPlaca;
    private javax.swing.JFormattedTextField TFPlaca1;
    private javax.swing.JFormattedTextField TFTipo;
    private javax.swing.JFormattedTextField TFValDiaria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labCPF;
    private javax.swing.JLabel labCPF1;
    private javax.swing.JLabel labFeedback;
    private javax.swing.JLabel labFeedback1;
    private javax.swing.JLabel labFeedback2;
    private javax.swing.JLabel labFeedback3;
    private javax.swing.JLabel labFeedback4;
    private javax.swing.JLabel labFeedback5;
    private javax.swing.JLabel labFeedback6;
    private javax.swing.JLabel labFeedback7;
    // End of variables declaration//GEN-END:variables
}
