package viewer;

import controller.GerInterGraf;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author joaom
 */
public class DlgCadastroCliente extends javax.swing.JDialog {
    private GerInterGraf gerIG;
    /**
     * Creates new form DlgCadastroCliente
     */
    public DlgCadastroCliente(java.awt.Frame parent, boolean modal, GerInterGraf gerIG) {
        super(parent, modal);
        this.gerIG = gerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBackground = new javax.swing.JPanel();
        PanTituloPag = new javax.swing.JPanel();
        LabTituloNovaReserva = new javax.swing.JLabel();
        PainelDados = new javax.swing.JPanel();
        LabCidade = new javax.swing.JLabel();
        LabDatNasc = new javax.swing.JLabel();
        TFNome = new javax.swing.JFormattedTextField();
        FTDatNasc = new javax.swing.JFormattedTextField();
        LabCPF = new javax.swing.JLabel();
        TFSenha = new javax.swing.JFormattedTextField();
        LabNome = new javax.swing.JLabel();
        LabCEP = new javax.swing.JLabel();
        TFCPF = new javax.swing.JFormattedTextField();
        TFCidade = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        TituloCad = new javax.swing.JLabel();
        PanBarraLateral = new javax.swing.JPanel();
        PanTitleBarraLateral = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        LabAluguelDeCarros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabIMGCarro = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanBackground.setForeground(new java.awt.Color(255, 255, 255));
        PanBackground.setMinimumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setPreferredSize(new java.awt.Dimension(1360, 720));
        PanBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTituloPag.setBackground(new java.awt.Color(150, 150, 150));
        PanTituloPag.setForeground(new java.awt.Color(150, 150, 150));
        PanTituloPag.setPreferredSize(new java.awt.Dimension(1050, 100));

        LabTituloNovaReserva.setBackground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabTituloNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setText("Cadastre-se");

        javax.swing.GroupLayout PanTituloPagLayout = new javax.swing.GroupLayout(PanTituloPag);
        PanTituloPag.setLayout(PanTituloPagLayout);
        PanTituloPagLayout.setHorizontalGroup(
            PanTituloPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanTituloPagLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        PanTituloPagLayout.setVerticalGroup(
            PanTituloPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTituloPagLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        PanBackground.add(PanTituloPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 110));

        PainelDados.setForeground(new java.awt.Color(255, 255, 255));
        PainelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabCidade.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabCidade.setText("Cidade");
        PainelDados.add(LabCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        LabDatNasc.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabDatNasc.setText("Data de Nascimento");
        PainelDados.add(LabDatNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        PainelDados.add(TFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 330, 36));

        try {
            FTDatNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        PainelDados.add(FTDatNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, 36));

        LabCPF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabCPF.setText("CPF");
        PainelDados.add(LabCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        try {
            TFSenha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        PainelDados.add(TFSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 79, 36));

        LabNome.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabNome.setText("Nome");
        PainelDados.add(LabNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        LabCEP.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabCEP.setText("CEP");
        PainelDados.add(LabCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        try {
            TFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        PainelDados.add(TFCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 79, 36));

        TFCidade.setToolTipText("");
        TFCidade.setPreferredSize(new java.awt.Dimension(488, 36));
        PainelDados.add(TFCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 330, 36));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        PainelDados.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        TituloCad.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TituloCad.setText("Informe as informações a seguir para realizar seu cadastro");
        PainelDados.add(TituloCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanBackground.add(PainelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 770, 390));

        PanBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setForeground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setMinimumSize(new java.awt.Dimension(370, 550));
        PanBarraLateral.setPreferredSize(new java.awt.Dimension(360, 720));
        PanBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitleBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanTitleBarraLateral.setForeground(new java.awt.Color(51, 51, 51));

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        LabPrimeDrive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabPrimeDrive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        LabAluguelDeCarros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        LabAluguelDeCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabAluguelDeCarros.setText("Aluguel de carros");
        LabAluguelDeCarros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabAluguelDeCarros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanTitleBarraLateralLayout = new javax.swing.GroupLayout(PanTitleBarraLateral);
        PanTitleBarraLateral.setLayout(PanTitleBarraLateralLayout);
        PanTitleBarraLateralLayout.setHorizontalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabPrimeDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanTitleBarraLateralLayout.setVerticalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(LabPrimeDrive))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanBarraLateral.add(PanTitleBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 370, 110));
        PanBarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 13));

        LabIMGCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CarroCadastro2.png"))); // NOI18N
        PanBarraLateral.add(LabIMGCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 610, 400));

        PanBackground.add(PanBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 560, -1));

        BotaoCadastrar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        PanBackground.add(BotaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 110, 30));

        BotaoCancelar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });
        PanBackground.add(BotaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        this.setVisible(false);
        gerIG.voltarPag(this);
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        this.setVisible(false);
        gerIG.voltarPag(this);
    }//GEN-LAST:event_BotaoCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JFormattedTextField FTDatNasc;
    private javax.swing.JLabel LabAluguelDeCarros;
    private javax.swing.JLabel LabCEP;
    private javax.swing.JLabel LabCPF;
    private javax.swing.JLabel LabCidade;
    private javax.swing.JLabel LabDatNasc;
    private javax.swing.JLabel LabIMGCarro;
    private javax.swing.JLabel LabNome;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabTituloNovaReserva;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PanBackground;
    private javax.swing.JPanel PanBarraLateral;
    private javax.swing.JPanel PanTitleBarraLateral;
    private javax.swing.JPanel PanTituloPag;
    private javax.swing.JFormattedTextField TFCPF;
    private javax.swing.JTextField TFCidade;
    private javax.swing.JFormattedTextField TFNome;
    private javax.swing.JFormattedTextField TFSenha;
    private javax.swing.JLabel TituloCad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
