/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerInterGraf;

/**
 *
 * @author joaom
 */
public class DlgHome extends javax.swing.JDialog {
    private GerInterGraf gerIG;
    /**
     * Creates new form DlgHome
     */
    public DlgHome(java.awt.Frame parent, boolean modal, GerInterGraf gerIG) {
        super(parent, modal);
        this.gerIG = gerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBackground = new javax.swing.JPanel();
        PanBarraLateral = new javax.swing.JPanel();
        PanTitleBarraLateral = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        LabAluguelDeCarros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BotaoNovaReserva = new javax.swing.JButton();
        BotaoReservas = new javax.swing.JButton();
        BotaoFeedBack = new javax.swing.JButton();
        PanTituloPagina = new javax.swing.JPanel();
        LabBemVindo = new javax.swing.JLabel();
        LabConhecaFrota = new javax.swing.JLabel();
        LabPropaganda = new javax.swing.JLabel();
        PanCarros = new javax.swing.JPanel();
        HB20S = new javax.swing.JLabel();
        Corolla = new javax.swing.JLabel();
        Nivus = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        LabNomeHB20S = new javax.swing.JLabel();
        LabValorHB20S = new javax.swing.JLabel();
        LabNomeCorolla = new javax.swing.JLabel();
        LabValorCorolla = new javax.swing.JLabel();
        LabNomeNivus = new javax.swing.JLabel();
        labValorNivus = new javax.swing.JLabel();
        PanVeiculosMaisAlugados = new javax.swing.JPanel();
        LabTituloCarros = new javax.swing.JLabel();
        PanBarraInferior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanBackground.setForeground(new java.awt.Color(242, 242, 242));
        PanBackground.setMaximumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setMinimumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setPreferredSize(new java.awt.Dimension(1360, 720));
        PanBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setForeground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setMinimumSize(new java.awt.Dimension(370, 550));
        PanBarraLateral.setPreferredSize(new java.awt.Dimension(360, 720));
        PanBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitleBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanTitleBarraLateral.setForeground(new java.awt.Color(51, 51, 51));

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        LabPrimeDrive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabPrimeDrive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        LabAluguelDeCarros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        LabAluguelDeCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabAluguelDeCarros.setText("Aluguel de carros");
        LabAluguelDeCarros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabAluguelDeCarros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanTitleBarraLateralLayout = new javax.swing.GroupLayout(PanTitleBarraLateral);
        PanTitleBarraLateral.setLayout(PanTitleBarraLateralLayout);
        PanTitleBarraLateralLayout.setHorizontalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabPrimeDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanTitleBarraLateralLayout.setVerticalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(LabPrimeDrive))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanBarraLateral.add(PanTitleBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 110));
        PanBarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 13));

        BotaoNovaReserva.setBackground(new java.awt.Color(70, 70, 70));
        BotaoNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/32x32/add.png"))); // NOI18N
        BotaoNovaReserva.setText("Nova Reserva");
        BotaoNovaReserva.setBorder(null);
        BotaoNovaReserva.setFocusPainted(false);
        BotaoNovaReserva.setFocusable(false);
        BotaoNovaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotaoNovaReserva.setIconTextGap(20);
        BotaoNovaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovaReservaActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoNovaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 80));

        BotaoReservas.setBackground(new java.awt.Color(70, 70, 70));
        BotaoReservas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoReservas.setForeground(new java.awt.Color(255, 255, 255));
        BotaoReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/32x32/notes_edit.png"))); // NOI18N
        BotaoReservas.setText("Minhas Reservas");
        BotaoReservas.setBorder(null);
        BotaoReservas.setFocusPainted(false);
        BotaoReservas.setIconTextGap(20);
        BotaoReservas.setMaximumSize(new java.awt.Dimension(163, 32));
        BotaoReservas.setMinimumSize(new java.awt.Dimension(163, 32));
        BotaoReservas.setPreferredSize(new java.awt.Dimension(163, 32));
        BotaoReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReservasActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 80));

        BotaoFeedBack.setBackground(new java.awt.Color(70, 70, 70));
        BotaoFeedBack.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoFeedBack.setForeground(new java.awt.Color(255, 255, 255));
        BotaoFeedBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/32x32/comments.png"))); // NOI18N
        BotaoFeedBack.setText("FeedBack");
        BotaoFeedBack.setBorder(null);
        BotaoFeedBack.setFocusPainted(false);
        BotaoFeedBack.setHideActionText(true);
        BotaoFeedBack.setIconTextGap(20);
        BotaoFeedBack.setMaximumSize(new java.awt.Dimension(163, 32));
        BotaoFeedBack.setMinimumSize(new java.awt.Dimension(163, 32));
        BotaoFeedBack.setPreferredSize(new java.awt.Dimension(163, 32));
        BotaoFeedBack.setVerifyInputWhenFocusTarget(false);
        BotaoFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFeedBackActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoFeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 80));

        PanBackground.add(PanBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        PanTituloPagina.setBackground(new java.awt.Color(150, 150, 150));
        PanTituloPagina.setForeground(new java.awt.Color(150, 150, 150));

        LabBemVindo.setBackground(new java.awt.Color(255, 255, 255));
        LabBemVindo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        LabBemVindo.setText("Bem Vindo!");

        javax.swing.GroupLayout PanTituloPaginaLayout = new javax.swing.GroupLayout(PanTituloPagina);
        PanTituloPagina.setLayout(PanTituloPaginaLayout);
        PanTituloPaginaLayout.setHorizontalGroup(
            PanTituloPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanTituloPaginaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LabBemVindo)
                .addContainerGap(783, Short.MAX_VALUE))
        );
        PanTituloPaginaLayout.setVerticalGroup(
            PanTituloPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTituloPaginaLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(LabBemVindo)
                .addGap(29, 29, 29))
        );

        PanBackground.add(PanTituloPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 1020, 110));

        LabConhecaFrota.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        LabConhecaFrota.setText("Conheça nossa Frota");
        PanBackground.add(LabConhecaFrota, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        LabPropaganda.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        LabPropaganda.setText("O melhor preço do mercado é aqui!");
        PanBackground.add(LabPropaganda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, -1));

        PanCarros.setBackground(new java.awt.Color(255, 255, 255));
        PanCarros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HB20S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/HB20S.png"))); // NOI18N
        PanCarros.add(HB20S, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, 170));

        Corolla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Corolla.png"))); // NOI18N
        PanCarros.add(Corolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 320, 180));

        Nivus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Nivus.png"))); // NOI18N
        PanCarros.add(Nivus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 310, 200));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PanCarros.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 10, 240));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PanCarros.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 10, 240));

        LabNomeHB20S.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabNomeHB20S.setText("HB20S Limited TGDI");
        PanCarros.add(LabNomeHB20S, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        LabValorHB20S.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabValorHB20S.setForeground(new java.awt.Color(0, 204, 0));
        LabValorHB20S.setText("- R$150,00 / Diária");
        PanCarros.add(LabValorHB20S, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        LabNomeCorolla.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabNomeCorolla.setText("Corolla XEi 2.0");
        PanCarros.add(LabNomeCorolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        LabValorCorolla.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabValorCorolla.setForeground(new java.awt.Color(0, 204, 0));
        LabValorCorolla.setText("- R$170,00 / Diária");
        PanCarros.add(LabValorCorolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        LabNomeNivus.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LabNomeNivus.setText("Nivus 1.0 TSI");
        PanCarros.add(LabNomeNivus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        labValorNivus.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labValorNivus.setForeground(new java.awt.Color(0, 204, 0));
        labValorNivus.setText("- R$210,00 / Diária");
        PanCarros.add(labValorNivus, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, -1));

        PanVeiculosMaisAlugados.setBackground(new java.awt.Color(0, 204, 0));

        LabTituloCarros.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        LabTituloCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabTituloCarros.setText("Veículos mais alugados");

        javax.swing.GroupLayout PanVeiculosMaisAlugadosLayout = new javax.swing.GroupLayout(PanVeiculosMaisAlugados);
        PanVeiculosMaisAlugados.setLayout(PanVeiculosMaisAlugadosLayout);
        PanVeiculosMaisAlugadosLayout.setHorizontalGroup(
            PanVeiculosMaisAlugadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanVeiculosMaisAlugadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LabTituloCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
        );
        PanVeiculosMaisAlugadosLayout.setVerticalGroup(
            PanVeiculosMaisAlugadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanVeiculosMaisAlugadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabTituloCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanCarros.add(PanVeiculosMaisAlugados, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1010, 50));

        PanBarraInferior.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout PanBarraInferiorLayout = new javax.swing.GroupLayout(PanBarraInferior);
        PanBarraInferior.setLayout(PanBarraInferiorLayout);
        PanBarraInferiorLayout.setHorizontalGroup(
            PanBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        PanBarraInferiorLayout.setVerticalGroup(
            PanBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        PanCarros.add(PanBarraInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        PanBackground.add(PanCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 1010, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoNovaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovaReservaActionPerformed
        gerIG.abrirDlgNovaReserva();
    }//GEN-LAST:event_BotaoNovaReservaActionPerformed

    private void BotaoReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReservasActionPerformed
        gerIG.abrirDlgReservas();
    }//GEN-LAST:event_BotaoReservasActionPerformed

    private void BotaoFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFeedBackActionPerformed
    }//GEN-LAST:event_BotaoFeedBackActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFeedBack;
    private javax.swing.JButton BotaoNovaReserva;
    private javax.swing.JButton BotaoReservas;
    private javax.swing.JLabel Corolla;
    private javax.swing.JLabel HB20S;
    private javax.swing.JLabel LabAluguelDeCarros;
    private javax.swing.JLabel LabBemVindo;
    private javax.swing.JLabel LabConhecaFrota;
    private javax.swing.JLabel LabNomeCorolla;
    private javax.swing.JLabel LabNomeHB20S;
    private javax.swing.JLabel LabNomeNivus;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabPropaganda;
    private javax.swing.JLabel LabTituloCarros;
    private javax.swing.JLabel LabValorCorolla;
    private javax.swing.JLabel LabValorHB20S;
    private javax.swing.JLabel Nivus;
    private javax.swing.JPanel PanBackground;
    private javax.swing.JPanel PanBarraInferior;
    private javax.swing.JPanel PanBarraLateral;
    private javax.swing.JPanel PanCarros;
    private javax.swing.JPanel PanTitleBarraLateral;
    private javax.swing.JPanel PanTituloPagina;
    private javax.swing.JPanel PanVeiculosMaisAlugados;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labValorNivus;
    // End of variables declaration//GEN-END:variables
}
