/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerInterGraf;
import controller.Util;
import domain.Cliente;
import domain.Contrato;
import domain.Locadora;
import domain.Veiculo;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joaom
 */
public class DlgNovaReserva extends javax.swing.JDialog {
    private GerInterGraf gerIG; 
    /**
     * Creates new form DlgNovaReserva
     */
    public DlgNovaReserva(java.awt.Frame parent, boolean modal, GerInterGraf gerIG) {
        super(parent, modal);
        this.gerIG = gerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LabTituloNovaReserva = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        PanCarros = new javax.swing.JPanel();
        PainelDados = new javax.swing.JPanel();
        labCPF = new javax.swing.JLabel();
        ftCPF = new javax.swing.JFormattedTextField();
        labLocadora = new javax.swing.JLabel();
        BotaoLimpar = new javax.swing.JButton();
        BotaoConfirmar1 = new javax.swing.JButton();
        labVeiculo = new javax.swing.JLabel();
        cmbVeiculos = new javax.swing.JComboBox<>();
        cmbLocadora = new javax.swing.JComboBox<>();
        labTotal = new javax.swing.JLabel();
        labParcelas = new javax.swing.JLabel();
        labFormPag = new javax.swing.JLabel();
        cmbFormPagamento = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfValTotal = new javax.swing.JTextPane();
        spnParcelas = new javax.swing.JSpinner();
        labValPar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfValParcela = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        labRet = new javax.swing.JLabel();
        labDev = new javax.swing.JLabel();
        dtChooserDatRetirada = new com.toedter.calendar.JDateChooser();
        dtChooserDatDevolucao = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        PanBarraLateral = new javax.swing.JPanel();
        PanTitleBarraLateral = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        LabAluguelDeCarros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BotaoNovaReserva = new javax.swing.JButton();
        BotaoReservas = new javax.swing.JButton();
        BotaoVeiculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        PanBackground.setForeground(new java.awt.Color(255, 255, 255));
        PanBackground.setMinimumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setPreferredSize(new java.awt.Dimension(1360, 720));
        PanBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(150, 150, 150));
        jPanel1.setForeground(new java.awt.Color(150, 150, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 100));

        LabTituloNovaReserva.setBackground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabTituloNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setText("Nova Reserva");

        BotaoVoltar.setBackground(new java.awt.Color(150, 150, 150));
        BotaoVoltar.setForeground(new java.awt.Color(150, 150, 150));
        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        BotaoVoltar.setBorder(null);
        BotaoVoltar.setBorderPainted(false);
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BotaoVoltar)
                .addGap(36, 36, 36)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoVoltar)
                    .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        PanBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 1020, 110));

        PanCarros.setBackground(new java.awt.Color(255, 255, 255));
        PanCarros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanBackground.add(PanCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 890, -1));

        labCPF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labCPF.setText("CPF");

        try {
            ftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCPF.setEnabled(false);

        labLocadora.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labLocadora.setText("Locadora");

        BotaoLimpar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoLimpar.setText("Limpar");
        BotaoLimpar.setToolTipText("");
        BotaoLimpar.setActionCommand("");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });

        BotaoConfirmar1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoConfirmar1.setText("Confirmar");
        BotaoConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConfirmar1ActionPerformed(evt);
            }
        });

        labVeiculo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labVeiculo.setText("Veiculo");

        cmbVeiculos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVeiculosItemStateChanged(evt);
            }
        });
        cmbVeiculos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbVeiculosFocusLost(evt);
            }
        });

        labTotal.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labTotal.setText("Valor Total");

        labParcelas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labParcelas.setText("Nº de Parcelas");

        labFormPag.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labFormPag.setText("Forma de Pagamento");

        cmbFormPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito", "Pix" }));

        tfValTotal.setEnabled(false);
        jScrollPane2.setViewportView(tfValTotal);

        spnParcelas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spnParcelas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnParcelasStateChanged(evt);
            }
        });

        labValPar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labValPar.setText("Valor Parcela");

        tfValParcela.setEnabled(false);
        jScrollPane3.setViewportView(tfValParcela);

        labRet.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labRet.setText("Data de Retirada");

        labDev.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labDev.setText("Data de Devolução");

        dtChooserDatRetirada.setDateFormatString("dd/MM/yyyy");

        dtChooserDatDevolucao.setDateFormatString("dd/MM/yyyy");
        dtChooserDatDevolucao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtChooserDatDevolucaoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labDev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtChooserDatDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labRet)
                        .addGap(21, 21, 21)
                        .addComponent(dtChooserDatRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labRet)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dtChooserDatRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dtChooserDatDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labDev)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelDadosLayout.createSequentialGroup()
                                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labFormPag))
                                .addGap(18, 18, 18)
                                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbFormPagamento, 0, 81, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(65, 65, 65)
                                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labValPar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addComponent(labCPF))
                        .addContainerGap(391, Short.MAX_VALUE))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PainelDadosLayout.createSequentialGroup()
                                    .addComponent(labVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(cmbVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelDadosLayout.createSequentialGroup()
                                        .addComponent(ftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCPF))
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labLocadora)
                            .addComponent(cmbLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)))
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labFormPag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbFormPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labValPar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(79, 79, 79)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        PanBackground.add(PainelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 940, 490));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Preencha os campos a seguir para realizar a reserva");
        PanBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        PanBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setForeground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setMinimumSize(new java.awt.Dimension(370, 550));
        PanBarraLateral.setPreferredSize(new java.awt.Dimension(360, 720));
        PanBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitleBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanTitleBarraLateral.setForeground(new java.awt.Color(51, 51, 51));

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        LabPrimeDrive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabPrimeDrive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        LabAluguelDeCarros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        LabAluguelDeCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabAluguelDeCarros.setText("Aluguel de carros");
        LabAluguelDeCarros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabAluguelDeCarros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanTitleBarraLateralLayout = new javax.swing.GroupLayout(PanTitleBarraLateral);
        PanTitleBarraLateral.setLayout(PanTitleBarraLateralLayout);
        PanTitleBarraLateralLayout.setHorizontalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabPrimeDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanTitleBarraLateralLayout.setVerticalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(LabPrimeDrive))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanBarraLateral.add(PanTitleBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 110));
        PanBarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 13));

        BotaoNovaReserva.setBackground(new java.awt.Color(85, 85, 85));
        BotaoNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovaReserva.setText("Nova Reserva");
        BotaoNovaReserva.setBorder(null);
        BotaoNovaReserva.setFocusPainted(false);
        BotaoNovaReserva.setFocusable(false);
        BotaoNovaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotaoNovaReserva.setIconTextGap(20);
        PanBarraLateral.add(BotaoNovaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 80));

        BotaoReservas.setBackground(new java.awt.Color(70, 70, 70));
        BotaoReservas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoReservas.setForeground(new java.awt.Color(255, 255, 255));
        BotaoReservas.setText("Minhas Reservas");
        BotaoReservas.setBorder(null);
        BotaoReservas.setFocusPainted(false);
        BotaoReservas.setIconTextGap(20);
        BotaoReservas.setMaximumSize(new java.awt.Dimension(163, 32));
        BotaoReservas.setMinimumSize(new java.awt.Dimension(163, 32));
        BotaoReservas.setPreferredSize(new java.awt.Dimension(163, 32));
        BotaoReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReservasActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 80));

        BotaoVeiculos.setBackground(new java.awt.Color(70, 70, 70));
        BotaoVeiculos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        BotaoVeiculos.setText("Veiculos Disponiveis");
        BotaoVeiculos.setBorder(null);
        BotaoVeiculos.setFocusPainted(false);
        BotaoVeiculos.setHideActionText(true);
        BotaoVeiculos.setIconTextGap(20);
        BotaoVeiculos.setMaximumSize(new java.awt.Dimension(163, 32));
        BotaoVeiculos.setMinimumSize(new java.awt.Dimension(163, 32));
        BotaoVeiculos.setPreferredSize(new java.awt.Dimension(163, 32));
        BotaoVeiculos.setVerifyInputWhenFocusTarget(false);
        BotaoVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVeiculosActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoVeiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 80));

        PanBackground.add(PanBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        gerIG.voltarPag(this);
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void BotaoConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConfirmar1ActionPerformed
        
        if(validarCampos()){
            Date dat_inicio = dtChooserDatRetirada.getDate();
            Date dat_fim = dtChooserDatDevolucao.getDate();
            Veiculo veiculo = (Veiculo) cmbVeiculos.getSelectedItem();
            double val_total =  (double) Util.calcularDiferencaEmDias(dat_inicio, dat_fim) * veiculo.getVal_diaria();
            int qtd_parcelas = (int) spnParcelas.getValue();
            double val_parcela = val_total * qtd_parcelas;
            Date dat_pagamento = dat_inicio;
            String forma_pagamento = cmbFormPagamento.getSelectedItem().toString();
            Cliente cliente = gerIG.getGerDominio().pesquisarPorCPF(ftCPF.getText());
            Locadora locadora = (Locadora) cmbLocadora.getSelectedItem();

            Contrato c = new Contrato(
                    dat_inicio,
                    dat_fim,
                    dat_pagamento,
                    forma_pagamento,
                    val_total,
                    val_parcela,
                    qtd_parcelas,
                    cliente,
                    veiculo,
                    locadora
                );
            
            if(c != null){
                gerIG.getGerDominio().inserir(c);

                //Ao contrato ser inserido, o veículo se torna indisponível e não pode ser alugado
                gerIG.getGerDominio().alterarEstadoVeiculo(veiculo);

                //ComboBox é recarregada para veículo alugado não aparecer mais
                gerIG.carregarComboVeiculosDisponíveis(cmbVeiculos);
                
                JOptionPane.showMessageDialog(this, "Reserva inserida com sucesso.", "Nova reserva", JOptionPane.INFORMATION_MESSAGE);  
                LimparCampos();
            }
            else{
                JOptionPane.showMessageDialog(this, "Erro na criação da reserva", "ERRO Reserva", JOptionPane.ERROR_MESSAGE );
            }
        }
        
    }//GEN-LAST:event_BotaoConfirmar1ActionPerformed

    private void BotaoReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReservasActionPerformed
        this.setVisible(false);
        gerIG.abrirDlgReservas();
    }//GEN-LAST:event_BotaoReservasActionPerformed

    private void BotaoVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVeiculosActionPerformed
        this.setVisible(false); //Evita que JDialogs sejam abertas uma sobre a outra repetidamente
        gerIG.abrirDlgVeiculos();
    }//GEN-LAST:event_BotaoVeiculosActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        gerIG.carregarComboVeiculosDisponíveis(cmbVeiculos);
        gerIG.carregarCombo(cmbLocadora, Locadora.class);
        cmbVeiculos.setSelectedIndex(0);
        ftCPF.setText(gerIG.getGerDominio().getUsuarioLogado().getCpf());
        
    }//GEN-LAST:event_formComponentShown

    private void cmbVeiculosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbVeiculosFocusLost
        atualizarValores();
    }//GEN-LAST:event_cmbVeiculosFocusLost

    private void spnParcelasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnParcelasStateChanged
        atualizarValores();
    }//GEN-LAST:event_spnParcelasStateChanged

    private void cmbVeiculosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVeiculosItemStateChanged
        atualizarValores();
    }//GEN-LAST:event_cmbVeiculosItemStateChanged

    private void dtChooserDatDevolucaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtChooserDatDevolucaoPropertyChange
        
        if(dtChooserDatRetirada.getDate() != null)
            atualizarValores();
    }//GEN-LAST:event_dtChooserDatDevolucaoPropertyChange

    private boolean validarCampos() {
        StringBuilder msgErro = new StringBuilder();

        // Resetar cores
        dtChooserDatRetirada.setForeground(Color.black);
        dtChooserDatDevolucao.setForeground(Color.black);
        ftCPF.setForeground(Color.black);
        labRet.setForeground(Color.black);
        labDev.setForeground(Color.black);
        labCPF.setForeground(Color.black);

        // Capturar datas
        Date dataRet = dtChooserDatRetirada.getDate();
        Date dataDev = dtChooserDatDevolucao.getDate();

        // Validar data de retirada
        if (dataRet == null) {
            msgErro.append("Informe a data de retirada.\n");
            labRet.setForeground(Color.red);
        }

        // Validar data de devolução
        if (dataDev == null) {
            msgErro.append("Informe a data de devolução.\n");
            labDev.setForeground(Color.red);
        }

        // Se ambas preenchidas, verificar ordem
        if (dataRet != null && dataDev != null && dataRet.after(dataDev)) {
            msgErro.append("A data de retirada deve ser antes da data de devolução.\n");
            labRet.setForeground(Color.red);
            labDev.setForeground(Color.red);
        }

        // Validar CPF
        String cpf = ftCPF.getText();
        if (cpf.isEmpty()) {
            msgErro.append("Informe um CPF.\n");
            labCPF.setForeground(Color.red);
        }

        // Se houver erro, mostrar diálogo
        if (msgErro.length() > 0) {
            JOptionPane.showMessageDialog(this, msgErro.toString(), "ERRO Reserva", JOptionPane.ERROR_MESSAGE );
            return false;
        }

        return true;
    }
    
    
    private void atualizarValores(){
        
        try{
            Veiculo v = (Veiculo) cmbVeiculos.getSelectedItem();
            Date dat_inicio = dtChooserDatRetirada.getDate();
            Date dat_fim = dtChooserDatDevolucao.getDate();

            double difDias = (double)(Util.calcularDiferencaEmDias(dat_inicio, dat_fim));
            if(difDias < 1) difDias = 1;


            if ( v != null && dat_inicio != null && dat_fim != null) {
                double valorTotal = difDias * v.getVal_diaria();

                tfValTotal.setText(String.valueOf(valorTotal));
                tfValParcela.setText(String.valueOf(valorTotal / (int) spnParcelas.getValue()));

            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Erro: Preencha os campos obrigarórios", "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);
            validarCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void LimparCampos(){
        dtChooserDatRetirada.cleanup();
        dtChooserDatDevolucao.cleanup();
        cmbVeiculos.setSelectedIndex(0);
        tfValTotal.setText("");
        spnParcelas.setValue(1);
        tfValParcela.setText("");
        cmbFormPagamento.setSelectedIndex(0);
        ftCPF.setText("");
        cmbLocadora.setSelectedIndex(0);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConfirmar1;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoNovaReserva;
    private javax.swing.JButton BotaoReservas;
    private javax.swing.JButton BotaoVeiculos;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel LabAluguelDeCarros;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabTituloNovaReserva;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PanBackground;
    private javax.swing.JPanel PanBarraLateral;
    private javax.swing.JPanel PanCarros;
    private javax.swing.JPanel PanTitleBarraLateral;
    private javax.swing.JComboBox<String> cmbFormPagamento;
    private javax.swing.JComboBox<String> cmbLocadora;
    private javax.swing.JComboBox<String> cmbVeiculos;
    private com.toedter.calendar.JDateChooser dtChooserDatDevolucao;
    private com.toedter.calendar.JDateChooser dtChooserDatRetirada;
    private javax.swing.JFormattedTextField ftCPF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labCPF;
    private javax.swing.JLabel labDev;
    private javax.swing.JLabel labFormPag;
    private javax.swing.JLabel labLocadora;
    private javax.swing.JLabel labParcelas;
    private javax.swing.JLabel labRet;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel labValPar;
    private javax.swing.JLabel labVeiculo;
    private javax.swing.JSpinner spnParcelas;
    private javax.swing.JTextPane tfValParcela;
    private javax.swing.JTextPane tfValTotal;
    // End of variables declaration//GEN-END:variables
}
