/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerInterGraf;

/**
 *
 * @author joaom
 */
public class DlgVeiculos extends javax.swing.JDialog {

    private GerInterGraf gerIG; 
    
    public DlgVeiculos(java.awt.Frame parent, boolean modal, GerInterGraf gerIG) {
        super(parent, modal);
        this.gerIG = gerIG;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LabTituloNovaReserva = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        PanCarros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanBarraLateral = new javax.swing.JPanel();
        PanTitleBarraLateral = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        LabAluguelDeCarros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BotaoNovaReserva = new javax.swing.JButton();
        BotaoReservas = new javax.swing.JButton();
        BotaoVeiculos = new javax.swing.JButton();
        PanTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabReservas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanBackground.setForeground(new java.awt.Color(255, 255, 255));
        PanBackground.setMinimumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setPreferredSize(new java.awt.Dimension(1360, 720));
        PanBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(150, 150, 150));
        jPanel1.setForeground(new java.awt.Color(150, 150, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 100));

        LabTituloNovaReserva.setBackground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabTituloNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setText("Veículos");

        BotaoVoltar.setBackground(new java.awt.Color(150, 150, 150));
        BotaoVoltar.setForeground(new java.awt.Color(150, 150, 150));
        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        BotaoVoltar.setBorder(null);
        BotaoVoltar.setBorderPainted(false);
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BotaoVoltar)
                .addGap(18, 18, 18)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(630, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoVoltar)
                .addGap(34, 34, 34))
        );

        PanBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 1020, 110));

        PanCarros.setBackground(new java.awt.Color(255, 255, 255));
        PanCarros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanBackground.add(PanCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 890, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Veiculos");
        PanBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        PanBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setForeground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setMinimumSize(new java.awt.Dimension(370, 550));
        PanBarraLateral.setPreferredSize(new java.awt.Dimension(360, 720));
        PanBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitleBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanTitleBarraLateral.setForeground(new java.awt.Color(51, 51, 51));

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        LabPrimeDrive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabPrimeDrive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        LabAluguelDeCarros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        LabAluguelDeCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabAluguelDeCarros.setText("Aluguel de carros");
        LabAluguelDeCarros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabAluguelDeCarros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanTitleBarraLateralLayout = new javax.swing.GroupLayout(PanTitleBarraLateral);
        PanTitleBarraLateral.setLayout(PanTitleBarraLateralLayout);
        PanTitleBarraLateralLayout.setHorizontalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabPrimeDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanTitleBarraLateralLayout.setVerticalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(LabPrimeDrive))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanBarraLateral.add(PanTitleBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 110));
        PanBarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 13));

        BotaoNovaReserva.setBackground(new java.awt.Color(70, 70, 70));
        BotaoNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovaReserva.setText("Nova Reserva");
        BotaoNovaReserva.setBorder(null);
        BotaoNovaReserva.setFocusPainted(false);
        BotaoNovaReserva.setFocusable(false);
        BotaoNovaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotaoNovaReserva.setIconTextGap(20);
        BotaoNovaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovaReservaActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoNovaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 80));

        BotaoReservas.setBackground(new java.awt.Color(70, 70, 70));
        BotaoReservas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoReservas.setForeground(new java.awt.Color(255, 255, 255));
        BotaoReservas.setText("Minhas Reservas");
        BotaoReservas.setBorder(null);
        BotaoReservas.setFocusPainted(false);
        BotaoReservas.setIconTextGap(20);
        BotaoReservas.setMaximumSize(new java.awt.Dimension(163, 32));
        BotaoReservas.setMinimumSize(new java.awt.Dimension(163, 32));
        BotaoReservas.setPreferredSize(new java.awt.Dimension(163, 32));
        BotaoReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReservasActionPerformed(evt);
            }
        });
        PanBarraLateral.add(BotaoReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 80));

        BotaoVeiculos.setBackground(new java.awt.Color(85, 85, 85));
        BotaoVeiculos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        BotaoVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        BotaoVeiculos.setText("Veiculos Disponiveis");
        BotaoVeiculos.setBorder(null);
        BotaoVeiculos.setFocusPainted(false);
        BotaoVeiculos.setHideActionText(true);
        BotaoVeiculos.setIconTextGap(20);
        BotaoVeiculos.setMaximumSize(new java.awt.Dimension(163, 32));
        BotaoVeiculos.setMinimumSize(new java.awt.Dimension(163, 32));
        BotaoVeiculos.setPreferredSize(new java.awt.Dimension(163, 32));
        BotaoVeiculos.setVerifyInputWhenFocusTarget(false);
        PanBarraLateral.add(BotaoVeiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 80));

        PanBackground.add(PanBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        TabReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabReservas);

        javax.swing.GroupLayout PanTabelaLayout = new javax.swing.GroupLayout(PanTabela);
        PanTabela.setLayout(PanTabelaLayout);
        PanTabelaLayout.setHorizontalGroup(
            PanTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        PanTabelaLayout.setVerticalGroup(
            PanTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        PanBackground.add(PanTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 890, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        gerIG.voltarPag(this);
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoNovaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovaReservaActionPerformed
        this.setVisible(false);
        gerIG.abrirDlgNovaReserva();
    }//GEN-LAST:event_BotaoNovaReservaActionPerformed

    private void BotaoReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReservasActionPerformed
        this.setVisible(false);
        gerIG.abrirDlgReservas();
    }//GEN-LAST:event_BotaoReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoNovaReserva;
    private javax.swing.JButton BotaoReservas;
    private javax.swing.JButton BotaoVeiculos;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel LabAluguelDeCarros;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabTituloNovaReserva;
    private javax.swing.JPanel PanBackground;
    private javax.swing.JPanel PanBarraLateral;
    private javax.swing.JPanel PanCarros;
    private javax.swing.JPanel PanTabela;
    private javax.swing.JPanel PanTitleBarraLateral;
    private javax.swing.JTable TabReservas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
