/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer;

import controller.GerInterGraf;
import controller.exceptions.AutenticacaoException;
import domain.Cliente;
import java.awt.Color;
import java.util.NoSuchElementException;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;

/**
 *
 * @author joaom
 */
public class FrmInicial extends javax.swing.JFrame {
    private GerInterGraf gerIG;
    /**
     * Creates new form FrmInicial
     */
    public FrmInicial(GerInterGraf newGerIG) {
        this.gerIG = newGerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBackground = new javax.swing.JPanel();
        PanTituloPag = new javax.swing.JPanel();
        LabTituloNovaReserva = new javax.swing.JLabel();
        PainelDados = new javax.swing.JPanel();
        labSenha = new javax.swing.JLabel();
        tfCPF = new javax.swing.JFormattedTextField();
        TituloCad = new javax.swing.JLabel();
        labCPF = new javax.swing.JLabel();
        tfSenha = new javax.swing.JTextField();
        TituloCad1 = new javax.swing.JLabel();
        BotaoEntrar = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanBarraLateral = new javax.swing.JPanel();
        PanTitleBarraLateral = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        LabAluguelDeCarros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabIMGCarro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanBackground.setForeground(new java.awt.Color(255, 255, 255));
        PanBackground.setMinimumSize(new java.awt.Dimension(1360, 720));
        PanBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTituloPag.setBackground(new java.awt.Color(150, 150, 150));
        PanTituloPag.setForeground(new java.awt.Color(150, 150, 150));
        PanTituloPag.setPreferredSize(new java.awt.Dimension(1050, 100));

        LabTituloNovaReserva.setBackground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabTituloNovaReserva.setForeground(new java.awt.Color(255, 255, 255));
        LabTituloNovaReserva.setText("Seja bem vindo ao Prime Drive!");

        javax.swing.GroupLayout PanTituloPagLayout = new javax.swing.GroupLayout(PanTituloPag);
        PanTituloPag.setLayout(PanTituloPagLayout);
        PanTituloPagLayout.setHorizontalGroup(
            PanTituloPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanTituloPagLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LabTituloNovaReserva)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        PanTituloPagLayout.setVerticalGroup(
            PanTituloPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTituloPagLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(LabTituloNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        PanBackground.add(PanTituloPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 110));

        PainelDados.setForeground(new java.awt.Color(255, 255, 255));
        PainelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labSenha.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labSenha.setText("Senha");
        PainelDados.add(labSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 30));

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        PainelDados.add(tfCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 36));

        TituloCad.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        PainelDados.add(TituloCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labCPF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        labCPF.setText("CPF");
        PainelDados.add(labCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 30));
        PainelDados.add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, 30));

        TituloCad1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TituloCad1.setText("Informe as informações a seguir para acessar sua conta");
        PainelDados.add(TituloCad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        BotaoEntrar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoEntrar.setText("Entrar");
        BotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntrarActionPerformed(evt);
            }
        });
        PainelDados.add(BotaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 110, 30));

        BotaoCadastrar.setBackground(new java.awt.Color(242, 242, 242));
        BotaoCadastrar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BotaoCadastrar.setForeground(new java.awt.Color(0, 51, 255));
        BotaoCadastrar.setText("Cadastrar-se");
        BotaoCadastrar.setBorder(null);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        PainelDados.add(BotaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, 20));

        jLabel1.setText("Não possui uma conta? ");
        PainelDados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        PanBackground.add(PainelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 770, 390));

        PanBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setForeground(new java.awt.Color(51, 51, 51));
        PanBarraLateral.setMinimumSize(new java.awt.Dimension(370, 550));
        PanBarraLateral.setPreferredSize(new java.awt.Dimension(360, 720));
        PanBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitleBarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        PanTitleBarraLateral.setForeground(new java.awt.Color(51, 51, 51));

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        LabPrimeDrive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabPrimeDrive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        LabAluguelDeCarros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        LabAluguelDeCarros.setForeground(new java.awt.Color(255, 255, 255));
        LabAluguelDeCarros.setText("Aluguel de carros");
        LabAluguelDeCarros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabAluguelDeCarros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanTitleBarraLateralLayout = new javax.swing.GroupLayout(PanTitleBarraLateral);
        PanTitleBarraLateral.setLayout(PanTitleBarraLateralLayout);
        PanTitleBarraLateralLayout.setHorizontalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabPrimeDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanTitleBarraLateralLayout.setVerticalGroup(
            PanTitleBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(LabPrimeDrive))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTitleBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabAluguelDeCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanBarraLateral.add(PanTitleBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 370, 110));
        PanBarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 13));

        LabIMGCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CarroCadastro2.png"))); // NOI18N
        PanBarraLateral.add(LabIMGCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 610, 400));

        PanBackground.add(PanBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarActionPerformed
        if(validarCampos()){
            try{
                Cliente cli = gerIG.getGerDominio().login(tfCPF.getText(), tfSenha.getText());
                
                gerIG.getGerDominio().setUsuarioLogado(cli);
                this.setVisible(false);
                gerIG.abrirDlgHome();
            } catch (HibernateException | ClassCastException | NoSuchElementException | AutenticacaoException ex) {
                    JOptionPane.showMessageDialog(this, "ERRO ao fazer login! Usuário ou senha inválidos", "Login", JOptionPane.ERROR_MESSAGE);
                    labCPF.setForeground(Color.red);
                    labSenha.setForeground(Color.red);
                }
        }
    }//GEN-LAST:event_BotaoEntrarActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        gerIG.abrirDlgCadastroCliente();
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    
    private boolean validarCampos() {
        StringBuilder msgErro = new StringBuilder();

        // Resetar cores
        tfCPF.setForeground(Color.black);
        tfSenha.setForeground(Color.black);


        // Validar CPF
        String cpf = tfCPF.getText();
        if (cpf.isEmpty()) {
            msgErro.append("Informe um CPF.\n");
            labCPF.setForeground(Color.red);
        }
        
        //Validar Senha
        String senha = tfSenha.getText();
        if (senha.isEmpty()) {
            msgErro.append("Informe uma senha.\n");
            labSenha.setForeground(Color.red);
        } 

        // Se houver erro, mostrar diálogo
        if (msgErro.length() > 0) {
            JOptionPane.showMessageDialog(this, msgErro.toString(), "ERRO Login", JOptionPane.ERROR_MESSAGE );
            return false;
        }

        return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoEntrar;
    private javax.swing.JLabel LabAluguelDeCarros;
    private javax.swing.JLabel LabIMGCarro;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabTituloNovaReserva;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PanBackground;
    private javax.swing.JPanel PanBarraLateral;
    private javax.swing.JPanel PanTitleBarraLateral;
    private javax.swing.JPanel PanTituloPag;
    private javax.swing.JLabel TituloCad;
    private javax.swing.JLabel TituloCad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labCPF;
    private javax.swing.JLabel labSenha;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables
}
